name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: blueocean-parent-$NEXT_PATCH_VERSION

replacers:
  - search: '/JENKINS-(\d+)/g'
    replace: 'https://issues.jenkins-ci.org/browse/JENKINS-$1'
exclude-lables:
  - internal
categories:
  - title: 🚀 Features
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
template: |
  ## What’s Changed

  $CHANGES
